apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: arecgis
        image: kowbee/arecgis:v1
        ports:
        - containerPort: 3001